# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exif_sort/ui/about.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(434, 264)
        self.verticalLayout = QtWidgets.QVBoxLayout(AboutDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.nameLabel = QtWidgets.QLabel(AboutDialog)
        self.nameLabel.setTextFormat(QtCore.Qt.AutoText)
        self.nameLabel.setObjectName("nameLabel")
        self.headerLayout.addWidget(self.nameLabel)
        self.versionLabel = QtWidgets.QLabel(AboutDialog)
        self.versionLabel.setObjectName("versionLabel")
        self.headerLayout.addWidget(self.versionLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.logoLabel = QtWidgets.QLabel(AboutDialog)
        self.logoLabel.setMaximumSize(QtCore.QSize(64, 64))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("exif_sort/ui/../res/icon.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")
        self.headerLayout.addWidget(self.logoLabel)
        self.verticalLayout.addLayout(self.headerLayout)
        self.aboutLayout = QtWidgets.QFormLayout()
        self.aboutLayout.setObjectName("aboutLayout")
        self.licenceLabel = QtWidgets.QLabel(AboutDialog)
        self.licenceLabel.setObjectName("licenceLabel")
        self.aboutLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.licenceLabel)
        self.licenceValueLabel = QtWidgets.QLabel(AboutDialog)
        self.licenceValueLabel.setObjectName("licenceValueLabel")
        self.aboutLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.licenceValueLabel)
        self.websiteLabel = QtWidgets.QLabel(AboutDialog)
        self.websiteLabel.setObjectName("websiteLabel")
        self.aboutLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.websiteLabel)
        self.websiteValueLabel = QtWidgets.QLabel(AboutDialog)
        self.websiteValueLabel.setOpenExternalLinks(True)
        self.websiteValueLabel.setObjectName("websiteValueLabel")
        self.aboutLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.websiteValueLabel)
        self.verticalLayout.addLayout(self.aboutLayout)
        self.librariesLabel = QtWidgets.QLabel(AboutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.librariesLabel.sizePolicy().hasHeightForWidth())
        self.librariesLabel.setSizePolicy(sizePolicy)
        self.librariesLabel.setOpenExternalLinks(True)
        self.librariesLabel.setObjectName("librariesLabel")
        self.verticalLayout.addWidget(self.librariesLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 33, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.footerLayout = QtWidgets.QHBoxLayout()
        self.footerLayout.setObjectName("footerLayout")
        self.copyrightLabel = QtWidgets.QLabel(AboutDialog)
        self.copyrightLabel.setObjectName("copyrightLabel")
        self.footerLayout.addWidget(self.copyrightLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.footerLayout.addItem(spacerItem2)
        self.closeButton = QtWidgets.QPushButton(AboutDialog)
        self.closeButton.setObjectName("closeButton")
        self.footerLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.footerLayout)

        self.retranslateUi(AboutDialog)
        self.closeButton.clicked.connect(AboutDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About"))
        self.nameLabel.setText(_translate("AboutDialog", "<html><head/><body><p><span style=\" font-size:20pt;\">EXIF Image Sorter</span></p></body></html>"))
        self.versionLabel.setText(_translate("AboutDialog", "{version}"))
        self.licenceLabel.setText(_translate("AboutDialog", "License:"))
        self.licenceValueLabel.setText(_translate("AboutDialog", "GNU General Public License v3.0 "))
        self.websiteLabel.setText(_translate("AboutDialog", "Website:"))
        self.websiteValueLabel.setText(_translate("AboutDialog", "<html><head/><body><p><a href=\"https://github.com/MGRINZ/exif-sort\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/MGRINZ/exif-sort</span></a></p></body></html>"))
        self.librariesLabel.setText(_translate("AboutDialog", "<html><head/><body><p>This software uses the following libraries to work:</p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Pillow (<a href=\"https://python-pillow.org/\"><span style=\" text-decoration: underline; color:#0000ff;\">website</span></a>)</li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PyQt5 (<a href=\"https://www.riverbankcomputing.com/software/pyqt/\"><span style=\" text-decoration: underline; color:#0000ff;\">website</span></a>)</li></ul></body></html>"))
        self.copyrightLabel.setText(_translate("AboutDialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Copyright @ 2023 MGRINZ</span></p></body></html>"))
        self.closeButton.setText(_translate("AboutDialog", "Close"))
